#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use cli\App;

$app = new App();

$app->registerCommand('hello', function (array $argv) use ($app) {
    $name = $argv[2] ?? "World";
    $app->getPrinterCmd()->display("Hello $name!!!");
});

$app->registerCommand('help', function (array $argv) use ($app) {
    $app->getPrinterCmd()->display("usage: prabbit hello [ your-name ]");
});

// UserPdo Commands
$app->registerCommand('user', function (array $argv) use ($app) {
    $method = $argv[2] ?? "all";
    $limit = $argv[3] ?? 10;
    $app->getPrinterCmd()->display("[RUN] prabbit $method $limit");
    $data = $app->getUserCmd()->$method($limit);
    $app->getPrinterCmd()->print($data);
});

$app->runCommand($argv);
